# Generated by Django 3.2.2 on 2021-05-12 18:13

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=250)),
                ('clasification', models.CharField(max_length=30)),
                ('imagen', models.ImageField(null=True, upload_to='')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=16)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=16)),
                ('factor', models.DecimalField(decimal_places=12, max_digits=16)),
                ('datetime', models.DateField(auto_now=True)),
                ('comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WalkUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('walkgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.group')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WalkContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=30)),
                ('purpose', models.CharField(max_length=30)),
                ('group_size', models.CharField(max_length=30)),
                ('familiarity', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.walkuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=30)),
                ('ability', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.walkuser')),
            ],
        ),
        migrations.CreateModel(
            name='DatoValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.dato')),
                ('value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.button')),
            ],
        ),
        migrations.CreateModel(
            name='DatoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='')),
                ('dato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.dato')),
            ],
        ),
        migrations.AddField(
            model_name='dato',
            name='context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.usercontext'),
        ),
        migrations.AddField(
            model_name='dato',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.walkuser'),
        ),
        migrations.AddField(
            model_name='dato',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.version'),
        ),
        migrations.AddField(
            model_name='dato',
            name='walk_context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.walkcontext'),
        ),
        migrations.AddField(
            model_name='button',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.version'),
        ),
    ]
