# Generated by Django 3.2.2 on 2021-05-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkuser',
            name='celphone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='clasification',
            field=models.CharField(blank=True, choices=[('Green', 'Good'), ('Yellow', 'Regular'), ('Red', 'Bad')], max_length=30, null=True),
        ),
    ]
