# Generated by Django 3.2 on 2021-06-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20210513_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
