# Generated by Django 3.2 on 2021-06-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False # <<<< THIS LINE
    dependencies = [
        ('control', '0003_alter_button_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dato',
            new_name='Data',
        ),
        migrations.RenameModel(
            old_name='DatoImagen',
            new_name='DataImagen',
        ),
        migrations.RenameModel(
            old_name='DatoValue',
            new_name='DataValue',
        ),
        migrations.RenameField(
            model_name='dataimagen',
            old_name='dato',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='datavalue',
            old_name='dato',
            new_name='data',
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='ability',
            field=models.CharField(blank=True, choices=[('Able', 'Able'), ('Impaired', 'Impaired'), ('Asisted', 'Asisted')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='age',
            field=models.CharField(blank=True, choices=[('Child', 'Child'), ('Teenager', 'Teenager'), ('Adult', 'Adult'), ('Elderly', 'Elderly')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='gender',
            field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='walkcontext',
            name='decision',
            field=models.CharField(blank=True, choices=[('Necessity', 'Necessity'), ('Choice', 'Choice')], max_length=30),
        ),
        migrations.AlterField(
            model_name='walkcontext',
            name='familiarity',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('Visitor', 'Visitor')], max_length=30),
        ),
        migrations.AlterField(
            model_name='walkcontext',
            name='group_size',
            field=models.CharField(blank=True, choices=[('Alone', 'Child'), ('With_a_dependent', 'With a dependent'), ('Group', 'Group')], max_length=30),
        ),
        migrations.AlterField(
            model_name='walkcontext',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Transport', 'Transport'), ('Leisure', 'Leisure')], max_length=30),
        ),
    ]
