# Generated by Django 3.2 on 2021-06-16 18:37

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False # <<<< THIS LINE
    dependencies = [
        ('control', '0004_auto_20210616_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataImagen',
            new_name='DataImage',
        ),
        migrations.RenameField(
            model_name='button',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='dataimage',
            old_name='imagen',
            new_name='image',
        ),
    ]
