# Generated by Django 3.2.5 on 2021-07-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20210616_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='tag',
        ),
        migrations.AddField(
            model_name='data',
            name='gpsaccuracy',
            field=models.DecimalField(decimal_places=12, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='perception',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=30),
        ),
        migrations.AddField(
            model_name='version',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='number_ver',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='clasification',
            field=models.CharField(blank=True, choices=[('green', 'Good'), ('yellow', 'Regular'), ('red', 'Bad')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='ability',
            field=models.CharField(blank=True, choices=[('able', 'Able'), ('impaired', 'Impaired'), ('asisted', 'Asisted')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='age',
            field=models.CharField(blank=True, choices=[('child', 'Child'), ('teenager', 'Teenager'), ('adult', 'Adult'), ('elderly', 'Elderly')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='gender',
            field=models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='walkcontext',
            name='decision',
            field=models.CharField(blank=True, choices=[('necessity', 'Necessity'), ('choice', 'Choice')], max_length=30),
        ),
        migrations.AlterField(
            model_name='walkcontext',
            name='familiarity',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('visitor', 'Visitor')], max_length=30),
        ),
        migrations.AlterField(
            model_name='walkcontext',
            name='group_size',
            field=models.CharField(blank=True, choices=[('alone', 'Alone'), ('with_a_dependent', 'With a dependent'), ('group', 'Group')], max_length=30),
        ),
        migrations.AlterField(
            model_name='walkcontext',
            name='purpose',
            field=models.CharField(blank=True, choices=[('transport', 'Transport'), ('leisure', 'Leisure')], max_length=30),
        ),
    ]
