# Generated by Django 3.2.5 on 2021-07-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20210728_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='country',
            field=models.CharField(blank=True, choices=[('brazil', 'Brazil'), ('chile', 'Chile'), ('england', 'England'), ('germany', 'Germany'), ('global', 'Global'), ('usa', 'USA')], max_length=20, null=True),
        ),
    ]
