# Generated by Django 3.2.5 on 2021-07-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20210728_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='nombre',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='tipo',
            field=models.CharField(blank=True, choices=[('vecindario', 'Vecindario'), ('municipal', 'Municipal')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='perception',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='country',
            field=models.CharField(blank=True, choices=[('brazil', 'Brazil'), ('chile', 'Chile'), ('england', 'England'), ('germany', 'Germany'), ('global', 'Global'), ('sweden', 'Sweden'), ('usa', 'USA')], max_length=30, null=True),
        ),
    ]
