# Generated by Django 3.2.6 on 2021-08-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_auto_20210729_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontext',
            name='ability',
            field=models.CharField(blank=True, choices=[('able', 'Able'), ('impaired', 'Impaired'), ('assisted', 'Assisted')], max_length=10),
        ),
    ]
