# Generated by Django 3.2.6 on 2021-08-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_alter_usercontext_ability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='factor',
        ),
        migrations.AlterField(
            model_name='version',
            name='number_ver',
            field=models.DateTimeField(null=True),
        ),
    ]
