# Generated by Django 3.2.6 on 2021-08-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_auto_20210820_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='number_ver',
            field=models.DateField(blank=True, null=True),
        ),
    ]
