# Generated by Django 3.2.6 on 2021-08-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_alter_version_number_ver'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontext',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='walkcontext',
            name='date_end',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='walkcontext',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='walkcontext',
            name='gpsaccuracy_end',
            field=models.DecimalField(decimal_places=12, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='walkcontext',
            name='gpsaccuracy_start',
            field=models.DecimalField(decimal_places=12, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='walkcontext',
            name='latitude_end',
            field=models.DecimalField(decimal_places=12, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='walkcontext',
            name='latitude_start',
            field=models.DecimalField(decimal_places=12, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='walkcontext',
            name='longitude_end',
            field=models.DecimalField(decimal_places=12, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='walkcontext',
            name='longitude_start',
            field=models.DecimalField(decimal_places=12, max_digits=16, null=True),
        ),
    ]
