# Generated by Django 3.2.6 on 2021-08-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_auto_20210823_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='datetime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='walkcontext',
            name='date_end',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
