# Generated by Django 3.2.6 on 2021-08-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_auto_20210823_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='version',
        ),
        migrations.AddField(
            model_name='button',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='walkcontext',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.version'),
        ),
        migrations.AlterField(
            model_name='group',
            name='nombre',
            field=models.CharField(default='N/N', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='tipo',
            field=models.CharField(blank=True, choices=[('neighborhood', 'Neighborhood'), ('municipal', 'Municipal')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='number_ver',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
