# Generated by Django 3.2.6 on 2021-11-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_auto_20210826_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkcontext',
            name='weather_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
