# Generated by Django 3.2.6 on 2021-12-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_walkcontext_weather_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkcontext',
            name='temperature',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='walkcontext',
            name='weather_codition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='walkcontext',
            name='weather_text',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
