# Generated by Django 3.2.6 on 2022-03-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_auto_20211202_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='tipo',
            new_name='group_type',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='nombre',
            new_name='name',
        ),
    ]
