# Generated by Django 3.2.6 on 2022-04-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_auto_20220321_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkcontext',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
