# Generated by Django 3.2.6 on 2022-05-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0019_walkcontext_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datavalue',
            unique_together={('data', 'value')},
        ),
    ]
