# Generated by Django 3.2.13 on 2022-06-28 07:01

import control.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_alter_datavalue_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkcontext',
            name='date_end2',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='walkcontext',
            name='disable_date_auto_now',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='version',
            field=models.ForeignKey(null=True, on_delete=models.SET(control.models.get_deleted_version_instance), to='control.version'),
        ),
        migrations.AlterField(
            model_name='data',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET(control.models.get_deleted_user_instance), to='control.walkuser'),
        ),
        migrations.AlterField(
            model_name='datavalue',
            name='value',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='control.button'),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET(control.models.get_deleted_user_instance), to='control.walkuser'),
        ),
        migrations.AlterField(
            model_name='walkcontext',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET(control.models.get_deleted_user_instance), to='control.walkuser'),
        ),
        migrations.AlterField(
            model_name='walkcontext',
            name='version',
            field=models.ForeignKey(null=True, on_delete=models.SET(control.models.get_deleted_version_instance), to='control.version'),
        ),
        migrations.AlterField(
            model_name='walkuser',
            name='walkgroup',
            field=models.ForeignKey(null=True, on_delete=models.SET(control.models.get_deleted_group_instance), to='control.group'),
        ),
    ]
