# Generated by Django 3.2.13 on 2022-06-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0021_auto_20220628_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkcontext',
            name='date_end',
        ),
    ]
