# Generated by Django 3.2.13 on 2022-06-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0022_remove_walkcontext_date_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walkcontext',
            old_name='date_end2',
            new_name='date_end',
        ),
    ]
