# Generated by Django 3.2.13 on 2022-07-12 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0023_rename_date_end2_walkcontext_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='datetime_new',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='walk_context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='control.walkcontext'),
        ),
    ]
