# Generated by Django 3.2.14 on 2022-07-19 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0024_auto_20220712_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavalue',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.button'),
        ),
    ]
