# Generated by Django 3.2.14 on 2022-07-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0025_alter_datavalue_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkuser',
            name='profile',
            field=models.CharField(blank=True, choices=[('contributor', 'Contributor'), ('licensed', 'Licensed')], default='contributor', max_length=20, null=True),
        ),
    ]
