# Generated by Django 3.2.14 on 2022-08-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0026_walkuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkuser',
            name='country',
            field=models.CharField(default='N/C', max_length=50, null=True),
        ),
    ]
