# Generated by Django 3.2.14 on 2022-09-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0027_walkuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkcontext',
            name='countryCode',
            field=models.CharField(default='N/C', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='walkuser',
            name='countryCode',
            field=models.CharField(default='N/C', max_length=7, null=True),
        ),
    ]
