# Generated by Django 3.2.14 on 2022-10-04 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0028_auto_20220910_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('iso3', models.CharField(max_length=6)),
                ('iso2', models.CharField(max_length=6)),
                ('numeric_code', models.CharField(max_length=6)),
                ('phone_code', models.CharField(max_length=18)),
                ('capital', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=20)),
                ('native', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(max_length=30)),
                ('subregion', models.CharField(max_length=30)),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=16)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=16)),
                ('emojiU', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='walkcontext',
            name='postalCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('state_code', models.CharField(max_length=6)),
                ('type', models.CharField(blank=True, max_length=80, null=True)),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=16, null=True)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=16, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gpsname', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('wikiDataId', models.CharField(max_length=10, null=True)),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=16)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=16)),
                ('postalCode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.state')),
            ],
        ),
    ]
