# Generated by Django 3.2.14 on 2022-11-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0029_auto_20221004_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='type',
            new_name='state_type',
        ),
        migrations.RemoveField(
            model_name='city',
            name='gpsname',
        ),
        migrations.AddField(
            model_name='walkcontext',
            name='city_tableid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GPSCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.city')),
            ],
            options={
                'unique_together': {('name', 'city')},
            },
        ),
    ]
