# Generated by Django 3.2.14 on 2023-01-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0030_auto_20221103_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkcontext',
            name='distance_new',
            field=models.DecimalField(decimal_places=5, max_digits=16, null=True),
        ),
    ]
